### ISSUE TITLE
Chef Supermarket

### ISSUE THREAD

**Issue by damacus** [nkts/chef-pulp#2]
Hi!

would you be apposed to putting this cookbook on the community site?

**Comment by nkts** [comment]
Why do you need it on Supermarket? Berkshelf can fetch it from Github without any problems.

**Comment by damacus** [comment]
Whilst is it possible to use berkshelf in that way, it isn't ideal as github isn't an versioned artefact repository in the same way supermarket is.

**Comment by nkts** [comment]
I'm not familiar with Supermarket internals, but  from my experience git has better versioning then Chef cookbooks.

**Comment by hanskreuger** [comment]
@nkts Berkshelf can only fetch it from Github when it's a direct dependent - any further down the tree and it disappears. This is by design as the Github support is there for development only, not distribution.

For Example:
Cookbook B > Cookbook A (github) hosted - This works ok, because in B's Berksfile, you specify the Github location.
However if Cookbook C, wants to consume B (and A), it now has to specify A's location in it's own Berksfile.

Your comment about git versioning is spot on with regards to source control versioning, however the important issue here is release versioning, which is done at a cookbook level, not at a git level.

Hope this helps!

**Comment by nkts** [comment]
@hanskreuger If Cookbook C requires Cookbook B (and Cookbook A) it will be looking for those cookbooks in Chef's server. Berksfile just provides way to specify cookbook source and put them into Chef server.
Is this Chef client's default behaviour try to resolve cookbook dependencies looking into Supermarket at first place?

**Comment by hanskreuger** [comment]
@nkts I was giving an example of Berkshelf dependencies - i'm not talking about the chef server/client here.

The situation we're trying to avoid is one where a consumer cookbook (ie a wrapper that include_recipes pulp in this case) has to specify dependent cookbooks in the Berksfile.

For example, my_nice_library cookbook might consume pulp by setting the following:
recipes/default.rb:
```ruby
include_recipe 'pulp'
```

metadata.rb:
```ruby
depends 'pulp', '~> 1.0.0'
```

Berksfile:
```ruby
source 'https://supermarket.chef.io'
metadata
```

This lets Berkshelf find dependencies from metadata and source them from the supermarket.
The alternative you suggest would be something like:

Berksfile:
```ruby
source 'https://supermarket.chef.io'
metadata
cookbook 'pulp', github: 'nkts/chef-pulp', branch: '1.0.0'
```

my_nice_library cookbook now has explicit knowledge about pulp. The biggest problem with this is that cookbook statements aren't propagated, so a consumer of my_nice_library has to put the same cookbook statement in that Berksfile. This rather dilutes the point of using Berkshelf in the first place :cry:

**Comment by nkts** [comment]
I have pushed v0.1.1 to Supermarket. tho I don't recommend to use it. I'm working on new and updated version. New releases will be tagged and pushed to Supermarket as well.
